import Providers from '@/components/Providers/providers'
import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';
import 'react-toastify/dist/ReactToastify.css';
import { getServerSession } from "next-auth/next"
import { authOptions } from "@/app/api/auth/[...nextauth]/route"

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children, 
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={montserrat.className}>
		<Providers session={session}>
          <Navbar />
		  {children}
          <Footer />
		</Providers>
        {/* Footer shouldn't be on all pages, but I put it here for testing purposes */}
	  </body>
    </html>
  )
}
